### ISSUE TITLE
Missing description how to set up Type Instance with AWS credentials

### ISSUE THREAD

**Issue by lukaszo** [capactio/website#48]
## Description

We have one for GCP https://github.com/capactio/website/blob/main/docs/example/mattermost-installation.md#instructions-1

We have manifests for AWS, like for RDS and Elasticsearch, we should have description how to use them.

Maybe we could rework Mattermost example so it have 3 paths. For local deployment, for AWS and for GCP.

Consider creating a new document where it's described how to create a Type Instances for AWS and GCP.

**Comment by pkosiec** [comment]
AC:
- Add AWS RDS scenario for Mattermost
- In separate document, describe how to create common TypeInstances (AWS nad GCP credentials) - how to generate credentials in AWS/GCP and how to create the TypeInstances

**Comment by pkosiec** [comment]
It would be also good to include description of the scenario with reusing existing DB, as AFAIK we don't have anywhere such description.

**Comment by lukaszo** [comment]
> It would be also good to include description of the scenario with reusing existing DB for Mattermost, as AFAIK we don't have anywhere such description.

I would leave it for a different example. Mattermost is already big with 3 different scenarios.
Maybe an example where we deploy Database and the reuse it with two different projects would be better.

**Comment by lukaszo** [comment]
closed in https://github.com/capactio/website/pull/56
