### ISSUE TITLE
Create a follow-up introduction blog post

### ISSUE THREAD

**Issue by pkosiec** [capactio/website#63]
## Description

Create a follow-up introduction blog post as suggested by @mszostok in https://github.com/capactio/website/pull/59#pullrequestreview-751211556:

- Use manifests from: https://github.com/capactio/hub-manifests/issues/34
- In a blog post:
   - Aggregate all the commands needed to run the example
   - Keep it short
   - In a short introduction, relate to previous blog post
- Share it on social media
- **Nice:** Add a follow-up issue for next blog post series
   - Describe usage of Neo4j and Argo

Make it short enough to be readable.

## Reason

First blog post was about high-level introduction, but we also need some quick start instructions for a newcomer.

**Comment by mszostok** [comment]
Regarding "(..) next blog post series", we can also thing about preparing short (~3min) demos for Capact introduction 

- Capact e2e architecture - high-level
- Capact installation
- Browse OCH content with CLI
- Run Action with Capact - install app
- Reuse existing DB while installation
- Capact upgrade
- Helm-based Content creation
- Terraform-based content creation

DoD:
- Use our video template
- English subtitles

**Comment by mszostok** [comment]
Consider to make CLI better: https://github.com/capactio/capact/issues/489#issuecomment-1021193633

**Comment by mszostok** [comment]
PRs:
- https://github.com/capactio/website/pull/99
- https://github.com/capactio/hub-manifests/pull/53


Follow-up issues:
- TBD
